### ISSUE TITLE
DirWatch will not run...

### ISSUE THREAD

**Issue by tenzion** [caronc/nzbget-dirwatch#4]
I am trying to install DirWatch on my Synology, but am still failing to make it work.

DirWatch: Process is already running in another instance (pid=2391)
DirWatch: [DEBUG] PID-File identifies PID 2391 (our PID is 16858):

I cannot make my Dropbox access work...

DirWatch: nzbget.conf(61): Invalid value for option "NzbDir" (/volume1/dropbox/nzb/): could not read information for directory /volume1/dropbox/nzb: errno 13,

How do I manage to setup Dropbox to make this work? My Dropbox is setup via the CloudSync app on my Synology where my Dropbox access is locally on my Synology...

Thanks for any help!

**Comment by caronc** [comment]
Hi,

Error 13 is a 'Permission Denied' error.

I don't own a Synology device; but i do realize they're really popular, so bear with me in some of my assumptions below:

NZBGet  _probably_ executes as it's own user (I'm guessing the user _nzbget_) and based on your problem, it would appear that any one of (or all of) these directories you identified are not accessible by it.

- /volume1/
- /volume1/dropbox/
- /volume1/dropbox/nzb/

You could try doing something like:
```bash
# Make sure the root folder is at least readable by everyone:
chmod 755 /volume1/

# Make sure your dropbox folder is only available to the owner,
# but additionally; make sure you've granted execute permission
# for other users on your system so that they can access content
# only if they know where it is:
chmod 711 /volume1/dropbox/

# Finally grant full read/write permissions to your nzb directory
# on your dropbox so that the application can clear away the
# nzb file once it's processed:
chmod 777  /volume1/dropbox/nzb/
```
A more secure way would be to add your nzbget user to the same group as the owner of the dropbox account. Then grant your group permissions access to these folders. Something like that would look could be set up like so:
```bash
# Assuming your username (who owns the dropbox account on
# your system) is 'tenzion'; add the nzbget user to your group:
usermod -G tenzion nzbget

# Note: I'm drawing at straws for the above example, i'm not sure
# if Synology creates these groups for you so that you can do things
# like this.  But if it does; then... well keep reading :)

# Now I'm repeating the above commands in the earlier example
# but things are much more secure as you're only allowing
# nzbget access to these directories instead of everyone.

# Make sure the root folder is readable by your group:
chmod 755 /volume1/

# Now restrict everyone from your dropbox directory
# except it's own and group (which nzbget is a part of
# now)
chmod 750 /volume1/dropbox/

# Grant your group read/write to your nzb directory
chmod 775  /volume1/dropbox/nzb/

```

Hope this helps! Let me know if you're still having trouble

**Comment by tenzion** [comment]
Thanks for your help and quick reply!

I managed to find a compiled version 18 of nzbget for Synology (otherwise, the official release is v16... and I having some difficulties making the scheduler work).
Furthermore, I changed the username/pass of nzbget to a different one and then DirWatch began to work!
I did not change anything in the DirWatch script.
